### ISSUE TITLE
:UPlay Question

### ISSUE THREAD

**Issue by blakekrpec** [nagaohiroki/dotfiles#6]
I am curious how you are enabling the functionality for :UPlay, :UPause, etc in unity.lua. Did you write c# scripts to handle this in Unity?

**Comment by nagaohiroki** [comment]
[NeovimIntegration.cs](https://github.com/nagaohiroki/NeovimForUnity/blob/main/NeovimForUnity/Assets/Packages/Editor/NeovimIntegration.cs)
[Messaging](https://github.com/nagaohiroki/NeovimForUnity/tree/main/NeovimForUnity/Assets/Packages/Editor/Messaging)

This is where it is mostly handled.
So this process depends on [NeovimForUnity](https://github.com/nagaohiroki/NeovimForUnity).

Messaging is created by referencing the Visual Studio Unity package.
https://docs.unity3d.com/Packages/com.unity.ide.visualstudio@2.0/manual/index.html

**Comment by nagaohiroki** [comment]
@blakekrpec 
lua/unity.lua moved [unity.nvim](https://github.com/nagaohiroki/unity.nvim)

**Comment by blakekrpec** [comment]
Thanks for heads up. I have been working with a modified unity.lua (removed python downloader), and have been wanting to move mine to a .nvim as well.
